version: "3.7"

volumes:
  m2:
  .cpcache:
  .shadow-cljs:

networks:
  server:
        
services:          
  server:
    image: ghcr.io/njordhov/docker-shadow-cljs
    build: .
    container_name: server  
    working_dir: /home
    networks:
      - server
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9630"]
      interval: 5s
      timeout: 30s
      retries: 12
    ports:
      - "9630:9630" 
      - "9090:9090"
      - "9099:9099"
      - "8080:8080"
    volumes:
      - .:/home
      - m2:/root/.m2
      - .cpcache:/tmp/.cpcache
      - .shadow-cljs:/tmp/.shadow-cljs
    entrypoint: 
      - npx
      - shadow-cljs 
      - server
  
  shadow-cljs:
    image: ghcr.io/njordhov/docker-shadow-cljs
    build: .
    depends_on:
      server:
        condition: service_healthy
    networks:
      - server
    network_mode: service:server
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
      - .cpcache:/.cpcache
      - .shadow-cljs:/.shadow-cljs
    entrypoint: 
      - npx
      - shadow-cljs
