version: "3.7"

volumes:
  m2:
  .cpcache:
  .shadow-cljs:

networks:
  server:
        
services:          
  server:
    container_name: server 
    image: ghcr.io/njordhov/docker-shadow-cljs:v0.3
    build: . 
    networks:
      - server
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9630"]
      interval: 10s
      timeout: 5s
      retries: 12
    ports:
      - "9630:9630" 
      - "9090:9090"
      - "9099:9099"
      - "8080:8080"
    volumes:
      - .:/home
      - m2:/root/.m2
      - .cpcache:/tmp/.cpcache
      - .shadow-cljs:/tmp/.shadow-cljs
    working_dir: /home
    entrypoint: 
      - /bin/bash 
      - -c 
      - 'test -f shadow-cljs.edn || npx shadow-cljs init && npx shadow-cljs server'      
  
  shadow-cljs:
    image: ghcr.io/njordhov/docker-shadow-cljs:v0.3
    build: .
    depends_on:
      server:
        condition: service_healthy
    networks:
      - server
    network_mode: service:server
    working_dir: /home
    volumes:
      - .:/home
      - m2:/root/.m2
      - .cpcache:/tmp/.cpcache
      - .shadow-cljs:/tmp/.shadow-cljs
    entrypoint: 
      - npx
      - shadow-cljs
